from vcatechnology/linux-mint

RUN apt update -y
RUN apt upgrade -y
RUN apt install vim -y
RUN apt install vim-gtk3 -y
RUN apt install bzip2 -y
RUN apt install btop -y
RUN apt install neofetch -y
RUN apt install pigz -y

CMD /usr/bin/bash
